In [1]:
# Chapter 7 - Metropolis algorithm

In [3]:
import numpy as N

In [49]:
myData = N.repeat([1,0],[7,3])

In [63]:
def Likelihood(theta,data):
    
    z = N.sum(data)
    n = len(data)
    if N.size(theta) == 1:
        pDataGivenTheta = 0
        if theta < 1 and theta > 0:
            pDataGivenTheta = theta**z * (1-theta)**(n-z)
    else:
        pDataGivenTheta = theta**z*(1-theta)**(n-z)
        # theta passed to this function are random and could inadvertently be beyond the [0,1] bounds
        pDataGivenTheta[(theta > 1) | (theta < 0)] = 0
    return pDataGivenTheta
    
def Prior(theta,form='uniform'):
    
    theta = N.array(theta)
    
    if form == 'uniform':
        if N.size(theta) == 1:
            prior = 0
            if theta < 1 and theta > 0:
                prior = 1
        else:
            prior = N.ones(len(theta)) # uniform density over [0,1]
            # in case the some of the thetas (generated randomly) passed are out of [0,1] bounds
            prior[(prior > 1) | (prior < 0)] = 0
    elif form == 'bimodal':
        from scipy.stats import beta 
        prior = beta.pdf(N.minimum(2*theta,2*(1-theta)),2,2) # equiv. to R's dbeta func.
        # in case the some of the thetas (generated randomly) passed are out of [0,1] bounds
        prior[(prior > 1) | (prior < 0)] = 0
    
    
    return prior

def TargetRelProb(theta,data):
    
    # calculates the un-normalized posterior distribution
    targRelProb = Likelihood(theta,data) * Prior(theta)
    return targRelProb

In [33]:
# Specify the length of the trajectory, i.e. the number of jumps to try:
trajLength = 11112 # arbitrary large number
# Initialize the vector that will store the results:
trajectory = N.zeros(trajLength)
# Specify where to start the trajectory:
trajectory[0] = 0.5 # arbitrary value
# Specify the burn-in period:
burnIn = N.ceil(0.1 * trajLength) # arbitrary number, less than trajLength
# Initialize accepted/rejected counters, just to monitor performance
nAccepted = 0
nRejected = 0
# Specify seed to reproduce same random walk
N.random.seed(47405)

# Now generate the random walk. The 't' index is time or trial in the walk

for t in range(trajLength-1):
    currPos=trajectory[t]
    # Use the proposal distribution to generate a proposed jump.
    # The shape/variance of the proposal distribution can be changed
    # to whatever you think is appropriate for the target distribution.
    proposedJump=N.random.normal(loc=0,scale=0.1,size=1)
    # Generate a random uniform value from the interval [0,1]
    acceptCrit = N.random.uniform(size=1)
    # Compute the probability of accepting the proposed jump:
    probAccept = N.minimum(1,TargetRelProb(currPos + proposedJump,myData)/TargetRelProb(currPos,myData))
    if acceptCrit < probAccept:
        # accept the proposed jump
        trajectory[t+1] = currPos + proposedJump
        #increment the acceptance counter (just to monitor performance)
        if t>burnIn:
            nAccepted += 1
    else:
        # reject the proposed jump, stay at current position
        trajectory[t+1] = currPos
        # increment the rejection counter
        if t>burnIn:
            nRejected += 1

#Extract the post burn-in part of the trajectory
acceptedTraj = trajectory[burnIn + 1:]

# END OF METROPOLIS ALGORITHM
#----------------------------------------------------------------------
# Display the posterior
    

In [36]:
N.random.normal(loc=0,scale=0.1,size=1)

array([-0.08711759])

In [64]:
theta=0.5-0.08711759
#Likelihood(theta,myData)
Prior(theta)

1

In [93]:
pj = N.random.normal(loc=0,scale=0.1,size=1)
N.minimum(1,TargetRelProb(0.5 + pj,myData)/TargetRelProb(0.5,myData))

array([ 0.39437099])

In [87]:
TargetRelProb(0.5,myData)

0.0009765625

In [72]:
pj=N.random.normal

In [77]:
for i in range(10):
   print pj(loc=0,scale=0.1,size=1)

[-0.07606061]
[ 0.14721866]
[-0.03405059]
[-0.01216837]
[-0.03528785]
[ 0.04941452]
[ 0.01068187]
[-0.04296744]
[-0.06138142]
[ 0.0073397]


In [85]:
N.random.uniform(size=1)

array([ 0.44077337])